# -*- coding: utf-8 -*-
"""NFHS-5 Bihar Child Nutrition Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-__enhGHW5Lh044AVebfC-fQ9aImF8x
"""

"""
NFHS-5 Bihar Child Nutrition Analysis
-------------------------------------

Simple EDA Project using Python
"""

# Importing libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading dataset

df = pd.read_csv("/content/drive/MyDrive/Sample Data Sets/NFHS-5 dataset — 706 districts, 109 columns.csv")

# Selecting Bihar data only

bihar = df[df['State/UT'] == 'Bihar']

# Selecting useful columns and creating a copy to avoid SettingWithCopyWarning

data = bihar[[
'District Names',
'Children under 5 years who are stunted (height-for-age)18 (%)',
'Children under 5 years who are wasted (weight-for-height)18 (%)',
'Children under 5 years who are underweight (weight-for-age)18 (%)',
'Children under age 6 months exclusively breastfed16 (%)',
'Institutional births (in the 5 years before the survey) (%)',
'Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)'
]].copy()
data.head()

# Renaming columns
data.columns = [
'District',
'Stunting',
'Wasting',
'Underweight',
'Breastfeeding',
'Institutional_Delivery',
'Child_Anaemia'
]

data.head()

# Converting columns into numeric values, cleaning, and handling missing values

for col in data.columns[1:]:
  # Convert to string first to handle string operations, then remove parentheses
  data[col] = data[col].astype(str).str.replace(r'[()]', '', regex=True)
  # Convert to numeric, coerce errors to NaN
  data[col] = pd.to_numeric(data[col], errors='coerce')
  # Replace NaN values with Median
  data[col] = data[col].fillna(data[col].median())
  # Ensure all values are positive
  data[col] = data[col].abs()

# Checking Data Type
data.dtypes

# Dataset information
print("\nShape of dataset :", data.shape)

# Missing values

print("\nMissing Values")
print(data.isnull().sum())

# Basic statistics

print("\nSummary Statistics")
print(data.describe())

# GRAPH 1 - Top 10 districts with highest stunting (Using Seaborn)
top10 = data.sort_values('Stunting', ascending=False).head(10)

plt.figure(figsize=(10, 7))

# Create the seaborn barplot (assigning hue fixes the v0.14.0 warning)
ax = sns.barplot(
    x='District',
    y='Stunting',
    data=top10,
    palette='Blues_r',
    hue='District',
    legend=False
)

# Add values on top of the bars
for container in ax.containers:
    ax.bar_label(container, fmt='%.1f%%', padding=3)

plt.xticks(rotation=45)
plt.ylabel("Stunting %")
plt.title("Top 10 Districts with Highest Stunting")
plt.tight_layout()
plt.show()

# GRAPH 2 - Stunting vs Wasting vs Underweight
compare = data[['District', 'Stunting', 'Wasting', 'Underweight']].sort_values('District', ascending=True)

# Melt the data to make it easy for Seaborn to plot grouped bars
df_melted = compare.melt(id_vars='District', var_name='Indicator', value_name='Percentage')

plt.figure(figsize=(20, 10))

# Plotting everything with one simple Seaborn command
sns.barplot(x='District', y='Percentage', hue='Indicator', width=0.8, gap=0.1, data=df_melted)

plt.xticks(rotation=90)
plt.ylabel("Percentage(%)")
plt.title("Malnutrition Indicators by District (Sorted by Stunting)")
plt.tight_layout()
plt.show()

# GRAPH 3 - Correlation Heatmap

corr = data.drop('District', axis=1).corr()

plt.figure(figsize=(8,6))

sns.heatmap(corr, annot=True)

plt.title("Correlation Heatmap")

plt.show()

print("""CONCLUSION Based on Heatmap :-

The Closest Connection (0.73): Underweight and Wasting have a strong positive link.
When a district faces sudden, acute weight loss (wasting), overall underweight numbers directly shoot up. They move hand-in-hand.

The Breastfeeding Shield (-0.43 & -0.40): Exclusive breastfeeding shows a clear negative correlation with both wasting and underweight.
It proves that better breastfeeding awareness directly keeps child malnutrition numbers down.

Hospital Births Benefit (-0.36): Higher rates of institutional deliveries are linked to lower stunting.
Proper healthcare at birth gives kids a healthier start, protecting them from long-term chronic growth issues.

The Malnutrition Surprise (-0.38): Interestingly, Stunting and Wasting are negatively correlated.
A district struggling with chronic stunting isn't necessarily the worst hit by sudden wasting—meaning they are driven by completely different regional factors!""")

# GRAPH 4 - Average Health Indicators

avg = {
'Stunting': data['Stunting'].mean(),
'Wasting': data['Wasting'].mean(),
'Underweight': data['Underweight'].mean(),
'Breastfeeding': data['Breastfeeding'].mean(),
'Anaemia': data['Child_Anaemia'].mean()
}

plt.figure(figsize=(8,5))

plt.bar(avg.keys(), avg.values())

plt.ylabel("Average Percentage (%)")
plt.title("Average Health Indicators in Bihar")

plt.show()

# Final Insights

print("\n------ Project Insights ------")

print("Average Stunting :", round(data['Stunting'].mean(),2))
print("Average Wasting :", round(data['Wasting'].mean(),2))
print("Average Underweight :", round(data['Underweight'].mean(),2))
print("Average Breastfeeding :", round(data['Breastfeeding'].mean(),2))
print("Average Institutional_Delivery :", round(data['Institutional_Delivery'].mean(),2))
print("Average Child Anaemia :", round(data['Child_Anaemia'].mean(),2))

print("\nDistrict with Highest Stunting :",data.loc[data['Stunting'].idxmax(), 'District'])
print("District with Lowest Stunting :", data.loc[data['Stunting'].idxmin(), 'District'])

print("\nDistrict with Highest Wasting :",data.loc[data['Wasting'].idxmax(), 'District'])
print("District with Lowest Wasting :", data.loc[data['Wasting'].idxmin(), 'District'])

print("\nDistrict with Highest Underweight :",data.loc[data['Underweight'].idxmax(), 'District'])
print("District with Lowest Underweight :", data.loc[data['Underweight'].idxmin(), 'District'])

print("\nDistrict with Highest Breastfeeding :",data.loc[data['Breastfeeding'].idxmax(), 'District'])
print("District with Lowest Breastfeeding :", data.loc[data['Breastfeeding'].idxmin(), 'District'])

print("\nDistrict with Highest Institutional_Delivery :",data.loc[data['Institutional_Delivery'].idxmax(), 'District'])
print("District with Lowest Institutional_Delivery :", data.loc[data['Institutional_Delivery'].idxmin(), 'District'])

print("\nDistrict with Highest Child Anaemia :",data.loc[data['Child_Anaemia'].idxmax(), 'District'])
print("District with Lowest Child Anaemia :", data.loc[data['Child_Anaemia'].idxmin(), 'District'])

print("\n*** Project Completed ***")

